-- AlterTable
ALTER TABLE "Almacen" ADD COLUMN     "fch_reg" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "flg_ok" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "reservado" BOOLEAN NOT NULL DEFAULT false;
